--- 
- name: Install nginx
  hosts: web
  become: yes

  tasks:
  - name: Ensure nginx package is present
    apt:
     name: nginx
     state: present

  - name: Ensure index.html is present
    copy:
     src: index.html
     dest: /var/www/html

  - name: Ensure nginx is started
    service:
     name: nginx
     state: started

- name: install db
  hosts: db
  become: yes

  tasks:
  - name: Ensure postrgesql package is present
    apt:
     name: postgresql
     state: present

  - name: Ensure postgresql service is present
    service:
     name: postgresql 
     state: started

