---
version: "3.3"
services:
  nexus:
    restart: always
    container_name: "nexus3_registry"
    image: sonatype/nexus3
    ports:
      - '8081:8081'
      - '8082:8082'
    volumes:
      - './nexus:/nexus-data'