FROM tomcat:9.0.65-jdk11-temurin
RUN apt-get update
RUN apt-get install docker -y
RUN apt-get install docker-compose -y
RUN apt-get install git -y
RUN apt-get install maven -y
RUN apt-get install default-jdk -y

