- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - ec2:
        key_name: mykey777
        image: ami-006d3995d3a6b963b
        instance_type: t2.micro
        security_group: MySecGroup777
        count: 1
        region: us-east-1
      register: result