---
# tasks file for sborka
- name: install java maven git packages
  apt: name={{item}} state:present
  with_items: 
   - default-jdk
   - maven
   - git

- name: clone git repository
  git:
   repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git  
   dest: /home/ubuntu/appgit
   clone: yes
   update: yes

- name: mvn packaging
  shell:
  cmd: mvn package
  chdir: /home/ubuntu/appgit

- name: Transfer java file to tomcat server
  synchronize 
   