---
# tasks file for sborka
- name: install java maven git packages
  apt: name={{item}} state=present
  with_items: 
   - default-jdk
   - maven
   - git

- name: clone git repository
  git:
   clone: yes
   repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git  
   dest: /home/ubuntu/appgit
   update: yes

- name: mvn packaging
  shell:
   cmd: mvn package
   chdir: /home/ubuntu/appgit

- name: copy java file from sborka node to local
  fetch:
   src: /home/ubuntu/appgit/target/hello-1.0.war 
   dest: /tmp/hello-1.0.war 