---
# tasks file for sborka
- name: install java maven git packages
  apt: name={{item}} state:present
  with_items: 
   - default-jdk
   - maven
   - git

- name: clone git repository
  git:
   repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git  
   dest: {{ git_dir }}
   clone: yes
   update: yes

- name: mvn packaging
  shell:
  cmd: mvn package
  dest: {{ git_dir }}

- name: copy java file from sborka node to local
  fetch:
   src: /home/user/appgit/target/hello-1.0.war 
   dest: /tmp/hello-1.0.war 