---
- name: install nginx
  hosts: demo3
  become: yes

  tasks:
    - name: Ensure java package is present
      apt:
        name: default-jdk
        state: present

    - name: Ensure maven package is present
      apt:
        name: maven
        state: present

    - name: Ensure git package is present
      apt:
        name: git
        state: present

    - name: clone git repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git 
        dest: /home/user/appgit
        clone: yes
        update: yes

    - name: MVN packaging
      shell: 
        cmd: mvn package
        chdir: /home/user/appgit

        