---
- name: install apps
  hosts: web
  become: yes

  tasks:
    - name: install java
      apt:
        name: defauly-jdk
        state: present

    - name: install git
      apt:
        name: maven
        state: present
