---
# tasks file for deploy
- name: ensure tomcat is present
  apt:
   name: tomcat9
   state: present

- name: transfer java file to tomcat server
  copy: 
   src: /tmp/hello-1.0.war 
   dest: /var/lib/tomcat9/webapps/
  notify: 
   - restart tomcat9