version: "3"
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
      - "8123:8123"
volumes:
  nexus-data: {}

# https://www.youtube.com/watch?v=2sBIT3dOTuw
# docker exec -it ubuntu_nexus_1 bash 
# cat /nexus-data/admin.password




